parameters:
    translation_directory: '%kernel.root_dir%/Resources/translations/'

services:
    static_translations.command:
        class: KunicMarko\StaticTranslationsBundle\Command\TranslateCommand
        arguments: ["%translation_directory%"]
        tags:
            - { name: console.command }
